### ISSUE TITLE
responsive tarif

### ISSUE THREAD

**Issue by clairebrnl** [WildCodeSchool/tlse0921-js-p2-BikeBuster#83]
la page des tarifs et particulièrement le tableau n'est pas responsive c'est un peu décalé sur le côté droite

**Comment by emmanouti** [comment]
les cards en dessous de la grille des tarifs ne sont pas symétriques et les boutons "voir le site" ne sont pas stylisés

**Comment by emmanouti** [comment]
manque un espace entre l'icone et le titre "tarif"
