### ISSUE TITLE
A propos

### ISSUE THREAD

**Issue by emmanouti** [WildCodeSchool/tlse0921-js-p2-BikeBuster#89]
Manque une majuscule au second paragraphe, "Qui sommes-nous ?" faute d'ortho, =
- accent vélib
- accessibilité (manque le i)
- bientôt 'ô'
- 8ème 'è'
- bijou sans 'x'
- est composée 
- p'tites têtes sinon ça fait comme un oubli
Des espaces inégaux entre les titres et les paragraphes. Le titre "À propos" manque l'accent (le titre est-il même nécessaire ? en version desktop c'est bizarre entre la barre nav et les cards de textes). 
Le carrousel en version desktop n'est pas centré et les noms des personnes sont trop transparents, on lit difficilement quand les photos sont sombres

**Comment by lauriepjs** [comment]
thank'ssss
