### ISSUE TITLE
tutoriels

### ISSUE THREAD

**Issue by emmanouti** [WildCodeSchool/tlse0921-js-p2-BikeBuster#90]
Prendre, faute d'ortho : 
- sélectionner 'é'
- Étape (alt 144 pour les intimes sur windows at least)
Déposer :
- pourquoi vous passez à l'impératif quand tout le tuto prendre est à l'infinitif
- verrouillé sans accent au premier e
- Étape également

**Comment by lauriepjs** [comment]
Ahaha je vais corriger ça direct merci Emma :)

**Comment by F-Anais** [comment]
emplacement : il manque le "l"
